install:
- pip install --user awscli
- wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_0.87.0_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version
before_script:
- rm -rf public
- hugo
script:
- aws s3 sync public/ s3://ecofuture.com --acl public-read --delete
- aws cloudfront create-invalidation --distribution-id E34JJYDV3ZLKUP --paths '/*'
branches:
 only:
 - master
 